


# resources/application.yml
server:
  port: 8081

spring:

  application:
    name: billingms

  datasource:
    url: jdbc:h2:mem:billingdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
